# Change these first
owner: iterate-ch # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: iterate GmbH Website
    url: https://iterate.ch/
    method: GET
  - name: iterate GmbH JIRA
    url: https://jira.iterate.ch/
    method: GET
  - name: iterate GmbH Bitbucket
    url: https://g.iterate.ch/
    method: GET
  - name: iterate GmbH Nextcloud
    url: https://cloud.iterate.ch/login
    method: GET
  - name: Cyberduck Website
    url: https://cyberduck.io/
    method: GET
  - name: Cyberduck Update Check
    url: https://version.cyberduck.io/
    method: GET
  - name: Cyberduck CLI
    url: https://duck.sh/
    method: GET
  - name: Cyberduck Trac
    url: https://trac.cyberduck.io/
    method: GET
  - name: Mountain Duck
    url: https://mountainduck.io/
    method: GET
  - name: Mountain Duck Update Check
    url: https://version.mountainduck.io/
    method: GET
  - name: Mountain Duck Payment Gateway
    url: https://reg.mountainduck.io/payment
    method: POST
    expectedStatusCodes:
      - 400
  - name: Cyberduck Payment Gateway
    url: https://reg.cyberduck.io/payment
    method: POST
    expectedStatusCodes:
      - 402
      
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://iterate.ch/img/iterate.svg
  name: Upptime iterate GmbH
  introTitle: "Uptime monitor and status page for iterate GmbH"
  introMessage: Status for sites managed by iterate GmbH
  navbar:
    - title: Status
      href: /
    - title: iterate GmbH
      href: https://iterate.ch/
