# Change these first
owner: iterate-ch # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: iterate GmbH Website
    url: https://iterate.ch/
    method: HEAD
  - name: iterate GmbH JIRA
    url: https://jira.iterate.ch/
    method: HEAD
  - name: iterate GmbH Bitbucket
    url: https://g.iterate.ch/
    method: HEAD
    expectedStatusCodes:
      - 302
  - name: Cyberduck Website
    url: https://cyberduck.io/
    method: HEAD
  - name: Cyberduck Update Check
    url: https://version.cyberduck.io/
    method: HEAD
  - name: Cyberduck CLI
    url: https://duck.sh/
    method: HEAD
  - name: Cyberduck Trac
    url: https://trac.cyberduck.io/
    method: HEAD
  - name: Mountain Duck
    url: https://mountainduck.io/
    method: HEAD
  - name: Mountain Duck Update Check
    url: https://version.mountainduck.io/
    method: HEAD
  - name: Mountain Duck Payment Gateway
    url: https://reg.mountainduck.io/payment
    method: POST
    expectedStatusCodes:
      - 400
  - name: Cyberduck Payment Gateway
    url: https://reg.cyberduck.io/payment
    method: POST
    expectedStatusCodes:
      - 403
      
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://iterate.ch/img/iterate.svg
  name: Upptime iterate GmbH
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status for sites managed by iterate GmbH
  navbar:
    - title: Status
      href: /
    - title: iterate GmbH
      href: https://iterate.ch/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
